# Generated by Django 2.0.1 on 2018-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefixes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='starting_from',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='starting_from_gln',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
