# Generated by Django 2.0.1 on 2018-01-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefixes', '0002_auto_20180117_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name_plural': 'prefixes'},
        ),
    ]
