# Generated by Django 2.0.1 on 2018-01-28 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('customer_role', models.CharField(default='', max_length=20)),
                ('agreed', models.BooleanField(default=False)),
                ('agreed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreed_version', models.CharField(default='', max_length=30, null=True)),
                ('login_count', models.IntegerField(null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='uam.Organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
