# Generated by Django 2.0.1 on 2018-01-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
