# Generated by Django 2.0.1 on 2018-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCM', '0004_auto_20180117_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.SlugField(default='admin', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
