# Generated by Django 2.0.1 on 2018-01-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCM', '0006_auto_20180126_2056'),
        ('BCM', '0006_auto_20180126_1032'),
    ]

    operations = [
    ]
