# Generated by Django 2.0.1 on 2018-01-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='AuditLog',
        ),
    ]
