# Generated by Django 2.0.1 on 2018-01-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20180117_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditLog',
            new_name='Log',
        ),
    ]
