# Generated by Django 2.0.1 on 2018-01-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
