# Generated by Django 2.0.1 on 2018-01-21 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_version',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
