# Generated by Django 2.0.1 on 2018-01-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BCM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(default='', max_length=100)),
                ('street1', models.CharField(default='', max_length=100)),
                ('street2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('gln', models.CharField(default='', max_length=13)),
                ('vat', models.CharField(default='', max_length=12)),
                ('credit_points_balance', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('prefix_override', models.CharField(default='', max_length=100)),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BCM.Country')),
            ],
        ),
    ]
