# Generated by Django 2.0.1 on 2018-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='credit_points_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisation',
            name='gln',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='prefix_override',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='street1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='street2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='vat',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='zip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
