# Generated by Django 2.0.1 on 2018-01-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uam', '0002_auto_20180114_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BCM.Country'),
        ),
    ]
