# Generated by Django 2.0.1 on 2018-01-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20180121_0631'),
        ('uam', '0002_auto_20180114_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(db_index=True, default='', max_length=14)),
                ('gs1_company_prefix', models.CharField(db_index=True, default='', max_length=75)),
                ('gln_of_information_provider', models.CharField(max_length=75)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='uam.Organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
        ),
    ]
