# Generated by Django 2.0.1 on 2018-01-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(db_index=True, default='', max_length=14)),
                ('gs1_company_prefix', models.CharField(db_index=True, default='', max_length=75)),
                ('gln_of_information_provider', models.CharField(max_length=75)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User')),
            ],
        ),
    ]
