# Generated by Django 2.0.1 on 2018-02-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=10)),
                ('image_path', models.CharField(default='', max_length=70)),
                ('description', models.TextField(default='')),
                ('ui_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
