# Generated by Django 2.0.1 on 2018-02-06 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(default='', max_length=20)),
                ('abbr', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='gross_weight_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_grossweight', to='products.WeightUOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_netweight', to='products.WeightUOM'),
        ),
    ]
