# Generated by Django 2.0.1 on 2018-02-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=100)),
                ('unit_descriptor', models.CharField(max_length=50)),
            ],
        ),
    ]
