# Generated by Django 2.0.1 on 2018-02-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0001_initial'),
        ('company_organisations', '0001_initial'),
        ('products', '0002_packagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company_organisations.CompanyOrganisation'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='functional_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gs1_cloud_state',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='member_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='member_organisations.MemberOrganisation'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_brand',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='website_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gln_of_information_provider',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
