# Generated by Django 2.0.1 on 2018-01-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180125_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gs1_company_prefix',
            field=models.CharField(blank=True, db_index=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uam.Organisation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.User'),
        ),
    ]
