# Generated by Django 2.0.1 on 2018-02-06 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180205_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('market', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='target_market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.TargetMarket'),
        ),
    ]
