# Generated by Django 2.0.1 on 2018-02-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180206_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='point_of_sale',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TargetMarket'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CountryOfOrigin'),
        ),
    ]
