# Generated by Django 2.0.1 on 2018-02-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180206_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='code',
            new_name='slug',
        ),
    ]
